### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by le2Ks** [softnote/softnote#1]
Hello, any discord group for the project?

**Comment by softnote** [comment]
Not currently. Would it be helpful?

**Comment by le2Ks** [comment]
It helps to build the community, so people can chat together about the project, the mining etc. Usually that<s what other crypto projects do. it<s not mandatory though of course.

**Comment by le2Ks** [comment]
Will you make one?

**Comment by softnote** [comment]
Probably not. You can make one though and I would be interested to see what is discussed and if anyone is having trouble using the software. There will be tutorial videos posted to the softnote youtube channel soon, showing and explaining how to use the software. https://www.youtube.com/channel/UCrlaF61ohMD8ofLA-_VpQ3g

**Comment by le2Ks** [comment]
Any exchange listing soon for the coin?

Also is there any explorer, official website etc..?
